defaults:
  - tokenizer_training_schema
  - tokenizer: bpe_tokenizer_config

data_parquet_path: gs://ymx-project-1-bucket-1/data/processed/rebalanced_splits/train.parquet
text_column_name: cleaned_text